import { sortOutfitsByNumber } from './seasonSort';

export const SERIES_GROUPS = [
  { key: 'dc', label: 'DC' },
  { key: 'marvel', label: 'Marvel' },
  { key: 'icon', label: 'Icon' },
  { key: 'gaming-legends', label: 'Gaming Legends' },
  { key: 'star-wars', label: 'Star Wars' },
  { key: 'cartoon', label: 'Cartoon Legends' },
  { key: 'anime-legends', label: 'Anime Legends' },
  { key: 'tv-legends', label: 'TV Legends' },
  { key: 'wwe-legends', label: 'WWE Legends' },
  { key: 'other-collab-skins', label: 'Other Collab Skins' },
  { key: 'general-collaborations', label: 'General Collaborations' },
  { key: 'nfl', label: 'NFL' },
  { key: 'anime-originals', label: 'Anime Originals' },
  { key: 'nanners', label: 'Nanners' },
  { key: 'joneseys', label: 'Joneseys' },
  { key: 'briters-and-bombers', label: 'Briters and Bombers' },
  { key: 'fishies', label: 'Fishies' },
  { key: 'ravens', label: 'Ravens' },
  { key: 'kitties', label: 'Kitties' },
  { key: 'team-leaders', label: 'Team Leaders' },
  { key: 'knights', label: 'Knights' },
  { key: 'space-voyagers', label: 'Space Voyagers' },
  { key: 'food', label: 'Food' },
  { key: 'toys', label: 'Toys' },
  { key: 'dancers-and-djs', label: "Dancers and DJ's" },
  { key: 'winterfest', label: 'Winterfest' },
  { key: 'fortnightmares', label: 'Fortnightmares' },
  { key: 'robots', label: 'Robots' },
  { key: 'easter-valentines', label: 'Easter & Valentines' },
  { key: 'forestry', label: 'Forestry' },
  { key: 'animals', label: 'Animals' },
  { key: 'sports', label: 'Sports' },
  { key: 'fire-and-ice', label: 'Fire & Ice' },
  { key: 'astral-entities', label: 'Astral Entities' },
  { key: 'aliens', label: 'Aliens' },
  { key: 'students-and-sorcery', label: 'Students and Sorcery' },
  { key: 'superhero-originals', label: 'Superhero Originals' },
  { key: 'no-sweat-summer', label: 'No Sweat Summer' },
  { key: 'ready-to-heist', label: 'Ready to Heist' },
  { key: 'imagined-order', label: 'Imagined Order' },
  { key: 'aerosol-and-auras', label: 'Aerosol & Auras' },
  { key: 'the-underground', label: 'The Underground' },
  { key: 'the-seven', label: 'The Seven' },
  { key: 'fox-clan', label: 'Fox Clan' },
  { key: 'midas-family', label: 'Midas Family' },
  { key: 'high-stakes-club', label: 'High Stakes Club' },
  { key: 'ruby-and-opal', label: 'Ruby & Opal' },
  { key: 'greek-gods', label: 'Greek Gods' },
  { key: 'other', label: 'Other' },
];

const SERIES_ORDER = new Map(SERIES_GROUPS.map((group, index) => [group.key, index]));

const CARTOON_OUTFIT_NAMES = new Set([
  'Rick Sanchez',
  'Mecha Morty',
  'Mr. Meeseeks',
  'Queen Summer',
  'Pickle Rick',
  'Rick Prime',
  'Space Beth',
  'Peter Griffin',
  'The Giant Chicken',
  'Cleveland Brown',
  'Lois Griffin',
  'Hank Hill',
  'Peggy Hill',
  'Bob Belcher',
  'Linda Belcher',
  'Danny Fenton',
  'Sam Manson',
  'Ed',
  'Mordecai',
  'Skips',
  'Eric Cartman',
  'Stan Marsh',
  'Kyle Broflovski',
  'Butters Stotch',
  'Kenny McCormick',
  'Homer Simpson',
  'Tighty Whities Homer',
  'Marge Simpson',
  'Lisa Simpson',
  'Bart Simpson',
  'Krusty the Clown',
  'Ned Flanders',
  'Scratchy',
  'Moe Szyslak',
  'Ben Tennyson',
  'Gwen Tennyson',
  'Invincible',
  'Omni-Man',
  'Atom Eve',
  'Dupli-Kate',
  'Allen the Alien',
  'Leonardo',
  'Michelangelo',
  'Donatello',
  'Raphael',
  'Shredder',
  'Super Shredder',
  "April O'Neil",
  'Casey Jones',
  'Bebop',
  'Rocksteady',
  "Krang's Android",
  'Korra',
  'Aang',
  'Katara',
  'Zuko',
  'Toph Beifong',
  'Avatar State Aang',
  'Buzz Lightyear',
  'Emperor Zurg',
  'Dr. Doofenshmirtz',
  'Buff Perry',
  'Frozone',
  'Mr. Incredible',
  'Mrs. Incredible',
  'Bugs Bunny',
  'Daffy Duck',
  'Lola Bunny',
  'Hercules',
  'Hades (Lord of the Dead)',
  'Megara',
  'He-Man',
  'She-Ra',
  'Skeletor',
  'Scooby-Doo',
  'Fred Jones',
  'Daphne Blake',
  'Velma Dinkley',
  'Shaggy Rogers',
  'Beavis',
  'Butt-Head',
  'Finn the Human',
  'Jake the Dog',
  'Princess Bubblegum',
  'Marceline',
  'Fionna the Human',
  'Cake the Cat',
  'Ice King',
  'The Earl of Lemongrab',
  'Hero Baymax',
  'Jack Skellington',
  'Sally',
  'Philip J. Fry',
  'Turanga Leela',
  'Bender Bending Rodríguez',
  'Pomni',
  'Jax',
  'Tom Lizard',
  'Cruella de Vil',
  'Captain Hook',
  'Maleficent',
  'Splinter',
]);

const ANIME_OUTFIT_NAMES = new Set([
  'Naruto Uzumaki',
  'Kakashi Hatake',
  'Sasuke Uchiha',
  'Sakura Haruno',
  'Itachi Uchiha',
  'Orochimaru',
  'Gaara',
  'Hinata Hyuga',
  'Son Goku',
  'Goku Black',
  'Bulma',
  'Beerus',
  'Vegeta',
  'Android 17',
  'Android 18',
  'Cell',
  'Frieza',
  'Son Gohan',
  'Piccolo',
  'Trunks',
  'Eren Jaeger',
  'Mikasa Ackermann',
  'Captain Levi',
  'All Might',
  'Izuku Midoriya',
  'Ochaco Uraraka',
  'Katsuki Bakugo',
  'Eijiro Kirishima',
  'Mina Ashido',
  'Shoto Todoroki',
  'Himiko Toga',
  'Dabi',
  'Tomura Shigaraki',
  'Kikoru Shinomiya',
  'Kafka Hibino',
  'Reno Ichikawa',
  'Yuji Itadori',
  'Streetwear Yuji Itadori',
  'Satoru Gojo',
  'Nobara Kugisaki',
  'Megumi Fushiguro',
  'Ryomen Sukuna',
  'Toji Fushiguro',
  'Mahito',
  'Saitama',
  'Terrible Tornado',
  'Genos',
  'Uryu Ishida',
  'Ichigo Kurosaki',
  'Rukia Kuchiki',
  'Orihime Inoue',
  'Spike Spiegel',
  'Faye Valentine',
]);

const TV_OUTFIT_NAMES = new Set([
  'Indiana Jones',
  'John Wick',
  'John Wick (Pen & Ink)',
  'Jon Snow',
  'Daenerys Targaryen',
  'Night King',
  'Black Dino Ranger',
  'White Dino Ranger',
  'Michael Scott',
  'Dwight Schrute',
  'Jules Winnfield',
  'Vincent Vega',
  'Doc Brown',
  'Marty McFly',
  'The Bride',
  'Yuki Yubari',
  'Gogo Yubari',
  'Vecna',
  'Mike Wheeler',
  'Will Byers',
  'Lucas Sinclair',
  'Dustin Henderson',
  'Xenomorph (Alien: Earth)',
  'Art the Clown',
  'Jason ',
  'The Grabber',
  'Ghost Face',
  'Ares (TRON)',
  'Lord Zedd',
  'Dino Megazord',
  'Yellow Ranger',
  'Black Ranger',
  'Pink Ranger',
  'Red Ranger',
  'Blue Ranger',
  'Green Ranger',
  'Front Man',
  'Games Guard',
  'Games Manager',
  'Negan',
  'Neytiri',
  'Jake Sully',
  'Leatherface',
  'Edward Scissorhands',
  'Billy',
  'Jack Sparrow',
  'Cursed Jack Sparrow',
  'Elizabeth Swann',
  'Captain Barbossa',
  'Davy Jones',
  'Michael Myers',
  'Megatron',
  'Bumblebee',
  'Optimus Prime',
  'Optimus Primal',
  'Adonis Creed',
  'Ash Williams',
  'RoboCop',
  'Nathan Drake',
  'Chloe Frazer',
  'Rick Grimes',
  'Paul Atreides',
  'Chani',
  "Frankenstein's Monster",
  'The Mummy',
  "Frankenstein's Bride",
  'Dude',
  'Mike Lowrey',
  'Xenomorph',
  'Godzilla Evolved',
  'Kong',
  'Mechagodzilla',
  'Ellen Ripley',
  'Snake Eyes',
  'T-800',
  'Sarah Connor',
  'Terminator',
  'Daryl Dixon',
  'Michonne',
  'El Chapulín Colorado',
  'Predator',
  'Chief Hopper',
  'Demogorgon',
  'Sofia',
  'Wednesday Addams',
  'Eleven',
]);

const OTHER_COLLAB_SKINS_OUTFIT_NAMES = new Set([
  'Tung Tung Tung Sahur',
  'Ballerina Cappuccina',
  'Plungerman',
  'Gildedguy',
  'Guggimon',
  'Janky',
  'Kelsier',
  'Yeddy',
  'Swooshman',
  'Maxxed Out Max',
  'Airphorian',
  'Eclipse',
  'Nike Goddess',
  'Maranello Racer',
  'Modena Icon',
  'Fashion Banshee',
  'Unchained Ramirez',
  'Game Knight',
  'Swish',
  'Hangtime',
  'Lyric',
  'Wilder',
  'Alto',
  'Sunset Alto',
  'Desert Dawn Lyric',
  'Throwback BG',
  'THE GOAT',
  'Goal Getter',
  'Poet',
  'Shady Doggo',
  'Clutch',
  'Grind',
  'Polo Prodigy',
  "Stadium Hero '92",
  'KAWS Skeleton',
  'FIRE Master Kai',
  'LIGHTNING Master Jay',
  'EARTH Master Cole',
  'ICE Master Zane',
  'Airie',
]);

const GENERAL_COLLABORATIONS_OUTFIT_NAMES = new Set([
  'Spirit Sniper',
  'Curse Buster',
  'Phantom Commando',
  'Specter Inspector',
  'Aura Analyzer',
  'Paranormal Guide',
  'Haunt Officer',
  'Ecto Expert',
  'Containment Specialist',
  'P.K.E. Ranger',
  'Rumblestrip',
  'Torque',
  'Marshal',
  'Powertrain',
  'RPM',
  'Camber',
  'Chicane',
  'Downforce',
  'Kickdown',
  'Circuit',
  'Guerrero Colorado',
  'Amazona Colorada',
  'Héroe Colorado',
  'Guerrera Colorada',
  'Agente Colorado',
  'Defensora Colorada',
  'Soldado Colorado',
  'Heroína Colorada',
  'Defensor Colorado',
  'Capitana Colorada',
  'Creature Caretaker',
  'Mischief Maker',
  'Knowledge Keeper',
  'Hallway Hero',
  'Fearless Friend',
  'Story Seeker',
  'Prank Prodigy',
  'Radiant Rebel',
  'Audacious Adventurer',
  'Dynamic Dreamer',
  'Gong-gi Great',
  'Flying Stone Fighter',
  'Jegi Juggler',
  'Pentathlon Perfector',
  'Glass Bridge Survivor',
  'Tug of War Titan',
  'Dalgona Destroyer',
  'Marble Maven',
  'Green Light Guardian',
  'Ddakji Defender',
  'Assist Maven',
  'Post Patroller',
  'Court Commander',
  'Layup Legend',
  'Rebound Warrior',
  'Trey Specialist',
  'Finesse Forward',
  'Board Crasher',
  'Court Controller',
  'Shuto Striker',
  'Mat Master',
  'Kumite Clasher',
  'Keri Commander',
  'Kata Captain',
  'Karateka Jones',
  'Heron Stance Hero',
  'Gi Guardian',
  'Dojo Defender',
  'Black Belt Brawler',
  'Splash Specialist',
  'Rebound Raider',
  'Rain Maker',
  'Half-Court Hero',
  'Fast Break',
  'Fadeaway',
  'Dynamo Dribbler',
  'Crossover Champion',
  'Buzzer Beater',
  'Upload',
  'Proxy',
  'Packet',
  'Io',
  'Firewall',
  'Datapath',
  'Cypher',
  'Commandline',
  'Bitstream',
  'Bandwidth',
  'Tiki Tackler',
  'Striker Specialist',
  'Shot Stopper',
  'Sgt. Sweeper',
  'Power Poacher',
  'Pitch Patroller',
  'Midfield Master',
  'Galactico',
  'Derby Dominator',
  'Breakaway',
  'Triple-Double',
]);

const NFL_OUTFIT_NAMES = new Set([
  'Pass Rush Ranger',
  'Scrimmage Scrapper',
  'Blitz Brigade',
  'Red Zone Renegade',
  'TD Titan',
  'Formation Fighter',
  'Punt Paragon',
  'Crossbar Crusher',
  'Snap Squad',
  'Trench Runner',
  'Fair Play',
  'Offside Officer',
  'Time-Out',
  'Elite Linesman',
  'Huddle Hero',
  'End Zone Expert',
  'Offense Overseer',
  'Replay Ranger',
  'Spiral Specialist',
  'Sideline Commander',
  'End Zone',
  'Gridiron',
  'Spike',
  'Blitz',
  'Rush',
  'Interceptor',
  'Juke',
  'Strong Guard',
  'Whistle Warrior',
  'Striped Soldier',
]);

const ANIME_ORIGINALS_OUTFIT_NAMES = new Set([
  'Erisa',
  'Court Queen Erisa',
  'Lennox Rose',
  'Belle Berry',
  'Zoe Clash',
  'Remi',
  'Lexa',
  'Princess Lexa',
  'Oathbound Lexa',
  'Alpine Lexa',
  'Lexa Hexbringer',
  'Orin',
  'Prince Orin',
  'Oathbound Orin',
  'Nurse Hikari',
  'Nurse Miyako',
  'Pi',
  'Retro Zoe Clash',
  'Chigusa',
  'Koi Agent Chigusa',
  'Imani',
  'Mae',
  'Battle Gamer Mae',
  'Reina',
  'Yuki',
  'Megumi',
  'Joss',
  'Greta Grim',
  'Grriz',
  'Nezumi',
  'Ready Penny',
  'Ricochet Rox',
]);

const WWE_OUTFIT_NAMES = new Set([
  'Liv Morgan',
  'Stone Cold Steve Austin',
  'Cody Rhodes',
  'Undertaker',
  'Becky Lynch',
  'Bianca Belair',
  'John Cena',
]);

const NANNERS_OUTFIT_NAMES = new Set([
  'Peely',
  'Springfielder Peely',
  'Unpeely',
  'The Final Peel',
  'Island Adventure Peely',
  'Peelverine',
  'Peelosopher Bananocrates',
  'Adventure Peely',
  'KAWSPEELY',
  'Toon Peely',
  'Polar Peely',
  'P33LY',
  'Potassius Peels',
  'Agent Peely',
  'Peely Bone',
  'P-1000',
  'Lil Split',
]);

const JONESEYS_OUTFIT_NAMES = new Set([
  'Ranger',
  'Captain Jones',
  'Vengeance Jones',
  'Championship Jonesy',
  'Jones Unchained',
  'Jonesy the Secondst',
  'Cozy Knit Jonesy',
  'Agent Jones',
  'Cozy Jonesy',
  'Jonesy The First',
  'Castaway Jonesy',
  'Relaxed Fit Jonesy',
  'Scuba Jonesy',
  'Slurp Jonesy',
  'Dark Jonesy',
  'Bunker Jonesy',
  'Guernsey',
  'Codename E.L.F.',
  'Lt. Evergreen',
]);

const BRITERS_AND_BOMBERS_OUTFIT_NAMES = new Set([
  'Brite Bomber',
  'Brite Gunner',
  'Brite Blaster',
  'Beach Bomber',
  'Brilliant Bomber',
  'Minty Bomber',
  'Britestorm Bomber',
  'Blizzard Bomber',
  'Froststorm Bomber',
  'Toon Bomber',
  'Brite Agent',
  'Brite Hunter',
  'BriteStar',
  'Brite Raider',
  'B.R.I.T.E.',
  'Dark Bomber',
]);

const FISHIES_OUTFIT_NAMES = new Set([
  'Fishstick',
  'Triggerfish',
  'Frozen Fishstick',
  'Atlantean Fishstick',
  'Fishskull',
  'Fa-La-La-La-Fishstick',
  'Toona Fish',
  'Gummy Fishstick',
  'Fish Thicc',
  'Bogstick',
  'Fishdrift',
  'Fishpool',
  'Robo-Fishstick',
  'Blinky Fishstick',
  'Contract Giller',
  'Princess Felicity Fish',
  'Stix',
]);

const RAVENS_OUTFIT_NAMES = new Set([
  'Raven',
  'Frozen Raven',
  'Ravenpool',
  'Graven',
  'Storm-Wild Raven',
  'Sir Raven',
  'Raven Team Syd',
  'Ravage',
  'Bone Ravage',
]);

const KITTIES_OUTFIT_NAMES = new Set([
  'Kit',
  'Bad Kit',
  'Katt',
  'Spice',
  'Meowscles',
  'Toon Meowscles',
  'Meow Skulls',
  'Purradise Meowscles',
  'Phantom Meowscles',
  'Meowtooth',
  'Meowdas',
  'Cate Meowdy',
  'Neko-RX1',
  'Lynx',
  'NeuraLynx',
  'Renegade Lynx',
  'Trailblazer Lynx',
  'Void Walker Lynx',
]);

const TEAM_LEADERS_OUTFIT_NAMES = new Set([
  'Cuddle Team Rider',
  'Wookiee Team Leader',
  'Cuddle Team Specialist',
  'Gummi Team Leader',
  'Raven Team Leader',
  'Metal Team Leader',
  'Quackling',
  'Clover Team Leader',
  'Mecha Team Leader',
  'Spooky Team Leader',
  'P.A.N.D.A Team Leader',
  'Fireworks Team Leader',
  'Cuddle Team Leader',
  'Ragsy',
  'Mecha Cuddle Master',
  'Mecha Team Shadow',
  'Cuddlepool',
  'Skull Squad Leader',
  'Bundles',
  'Snuggs',
  'Curdle Scream Leader',
  'Mecha Strike Commander',
  'Syd',
]);

const KNIGHTS_OUTFIT_NAMES = new Set([
  'Royale Knight',
  'Blue Squire',
  'Black Knight',
  'Red Knight',
  'Spider Knight',
  'Frozen Red Knight',
  'Ultima Knight',
  'Dark Red Knight ',
  'Rogue Spider Knight',
  'Eternal Knight',
  'Omega Knight',
  'Swamp Knight',
  'Core Knight Talus',
  'Spectra Knight',
  'Knightmare',
  'Ultima Carver',
  'Knight Conqueror',
  'Blitz Knight',
  'The Dark Maw',
  'Magmatic Carver',
  'Boss Obsidian',
  'O.M.E.G.A. Suit Alpha',
  'Oblivion',
  'Omega',
  'Danger Zone',
  'Gildhart',
]);

const SPACE_VOYAGERS_OUTFIT_NAMES = new Set([
  'Voyager Unleashed',
  'Dark Voyager (Reality Redacted)',
  'Dark Voyager',
  'Eternal Voyager',
  'Deo',
  'Siona',
  'Corrupted Voyager',
  'Eternal Wanderer',
  'Moonwalker',
  'Mission Specialist',
  'Leviathan',
  'Slurp Leviathan ',
  'Dark Vanguard',
  'Explorer Luna',
  'Cosma',
  'Horizon',
  'Starwalker',
  'Starflare',
]);

const FOOD_OUTFIT_NAMES = new Set([
  'Lil Whip',
  'Doughberman',
  'Peabody',
  'Mad Mochi',
  'Mancake',
  'Major Mancake',
  'Cobb',
  'Mincemeat',
  'Tart Tycoon',
  'Crustina',
  'Lada',
  'Beef Boss',
  'Jellie',
  'Color Splash Jellie',
  'Lumi Jellie',
  'Zzaria The Cruel',
  'Surrr Burger',
  'Pico de Gallant',
  'Pineapple Pete',
  'Brock',
  'Durrr Taisho',
  'Sizzle',
  'Ghost Ri-Durrr',
  'Onesie',
  'Wonder Onesie',
  'Sizzle Sgt. ',
  'Grill Sergeant',
  'Guaco',
  'Gumbo',
  'The Brat',
  'Constable Sprinkle',
  'Joey Caliente',
  'Kernel Poppy',
  'Big Dill',
  'Tomatohead',
  'Bao Bros',
  'Hothouse ',
  'Bone Boss',
  'Nash Nori',
  'Nightshade',
  'Gutbomb',
  'Dee',
  'PJ Pepperoni',
]);

const TOYS_OUTFIT_NAMES = new Set([
  'Monks',
  'Shadow Monks',
  'GHOST Monks',
  'Toy Trooper',
  'Plastic Patroller',
  'Bendie',
  'Twistie',
  'Crackshot',
  'Crackabella',
  'Boxer',
  'Boxy',
  'Holiday Boxy',
  'Hit Man',
  'Dummy',
  'Dummy Supreme',
  'Summer Dummy',
  'Wastelander Dummy',
  'Glacial Dummy',
  'The Ron-troller',
  'Ruck',
  'Signal',
  'Megg',
  'Webster',
  'Nitrojerry',
  'Snap',
  'Splode',
  'Airhead',
  'Diamond Hanz',
  'Dahlia',
  'Styx',
  'Guff',
]);

const THE_SEVEN_OUTFIT_NAMES = new Set([
  'The Imagined',
  'The Order',
  'The Guardian',
  'The Order (Reforged)',
  'The Foundation',
  'The Foundation (Reforged)',
  'The Visitor',
  'The Visitor (Reality Unknown)',
  'Paradigm (Reality-659)',
  'The Paradigm',
  'The Origin',
  'The Scientist',
]);

const FOX_CLAN_OUTFIT_NAMES = new Set([
  'Drift',
  'Vi',
  'Kimiko Five-Tails',
  'Catalyst',
  'Vox Hunter',
  'Stray',
  'Serge',
  'Rift Strider Drift',
  'Skulldrifter',
  'Summer Drift',
  'Snow Drift',
  'Driftwalker',
  'Riftreaver Drift',
]);

const MIDAS_FAMILY_OUTFIT_NAMES = new Set([
  'Midas',
  'Oro',
  'Midas Rex',
  'Orelia',
  'Midsummer Midas',
  'Shadow Midas',
  'Icebound Midas',
  'Golden Gear Midas',
  'Ascendant Midas',
  'Outlaw Midas',
  'Jules',
  'Scrapknight Jules',
  'Beach Jules',
  'Combat Tech Jules',
  'Elite Jules',
  'Lady Marigold',
  'Marigold',
  'Rebel Oro',
  'Skellemint Oro',
  'Brutus',
  'Beach Brutus',
  'Skye',
  'Summer Skye',
  'Winter Wonder Skye',
  'Undercover Skye',
  'TNTina',
  'Dynamo TNTina',
  'Gear Specialist Maya',
]);

const HIGH_STAKES_CLUB_OUTFIT_NAMES = new Set([
  'Joni the Red',
  'Helsie',
  'Lucien West',
  'Joni the Scarlet',
  'Huntress Helsie',
  'Formal Lucien West',
  'Helsie Midnight',
  'Red Ruin Joni',
  'Lycan West',
]);

const GREEK_GODS_OUTFIT_NAMES = new Set([
  'Zeus',
  'Ares',
  'Hades',
  'Aphrodite',
  'Artemis',
  'Polus',
  'Poseidon',
  'Cerberus',
  'Medusa',
  'Apollo',
  'Heartseeker Aphrodite',
  'Perseus',
  'Olympian',
  'Underworld Commander',
]);

const RUBY_AND_OPAL_OUTFIT_NAMES = new Set([
  'Ruby',
  'Ruby Shadows',
  'Boardwalk Ruby',
  'Dark Ruby',
  'Redway Ruby',
  'Opal',
  'Snow Opal',
]);

const ICON_OUTFIT_NAMES = new Set([
  'Triple Threat Moxie',
  'Triple Threat Reddysh',
  'Triple Threat Sommerset',
]);

const DANCERS_AND_DJS_OUTFIT_NAMES = new Set([
  'DJ Yonder',
  'Y0ND3R',
  'Stratus',
  'DJ Bop',
  'Liteshow',
  'Nitelite',
  'Sparkle Specialist',
  'Funk Ops',
  'Bunnywolf',
  'LLion',
  'Party Diva',
  'Party Star',
  'Party MVP',
  'Party Starter',
  'Nightlife',
  'Sabina',
  'Soiree',
  'Evie',
  'Summitseeker Evie',
  'Apprentice Evie',
  'Evie X',
  'Yon Dar 3000',
  'Sparkle Supreme',
  'Sparkle Diva',
  'Disco Diva',
  'PJ',
  'Hana Park',
  'Yoo-mi',
  'Champion PJ',
  'Stage Slayer',
  'Venus Hart',
  'Heatwave PJ',
  'Mullet Marauder',
  'Aerobic Assassin',
]);

const WINTERFEST_OUTFIT_NAMES = new Set([
  'Krampus',
  'Slushy Soldier',
  'Snowstrike',
  'Snowfoot',
  'Trog',
  'Tinseltoes',
  'Glimmer',
  'Grimbles',
  'Red-nosed Ranger',
  'Sugarplum',
  'Nog Ops',
  'Red-Nosed Raider',
  'Ginger Gunner',
  'Merry Marauder',
  'Yuletide Ranger',
  'Globe Shaker',
  'Kane',
  'Frozen Nog Ops',
  'The Devourer',
  'Cutiepie',
  'Wooly Warrior',
  'Cozy Commander',
  'Holly Jammer',
  'Jolly Hammer',
  'PJ Patroller',
  'Gingerbread Raider',
  'Snowmando',
  'Blinky',
  'Mr. Dappermint',
  'Snowbell',
  'Karve',
  'Holly Striker',
  'Guff Gringle',
  'Sled Ready Guff',
  'Arctic Adeline',
  'Cobalt Snowfoot',
  'Guffmas Tree',
  'Yulejacket',
  'Snowy Ops',
  'The Winterfest Bandit',
  'Sgt. Winter',
  'Lt. Winter',
  'Chilly',
  'Frosted Flurry',
  'Frost Squad',
  'Jolly Jammer',
  'Snow Patroller',
]);

const FORTNIGHTMARES_OUTFIT_NAMES = new Set([
  'Jack Gourdon',
  'Hollowhead',
  'Skull Trooper ',
  'Skull Ranger',
  'Yule Trooper',
  'Party Trooper',
  'Skull Commander',
  'Skull Raider',
  'Sparkle Skull',
  'Straw Ops',
  'Ghoul Trooper',
  'Baba Yaga',
  'Patch',
  'Headlock',
  'Punk',
  'The Good Doctor',
  'Ravina',
  'Skeletara',
  'Tricksy',
  'Sinister Glare',
  'Undying Sorrow',
  'Bonejamin',
  'Chrome Punk',
  "Jack O'Sassin",
  'Phantom Guff',
  'Pumpkin King',
  'Rotten Penny',
  'The Mothman',
  "All-Hallow's Steve",
  'Pig the Butcher',
  'Gnash',
  'Teef',
  'Big Mouth',
  'Scourge',
  'Plague',
  'Hay Man',
]);

const ROBOTS_OUTFIT_NAMES = new Set([
  'Tsuki',
  'Tsuki 2.0',
  'Designer Tsuki',
  'Sentinel',
  'Kitbash',
  'Rebel',
  'Revolt',
  'A.I.M.',
  'Eon',
  'Bryce 3000',
  'Zyg',
  'Lok-Bot',
  'CRZ-8',
  'Robo-Kevin',
  'Mecha-Pop',
  'BattleBus',
  'Dr. VinderBot',
  'Beastmode',
  'Iconica Prime',
  'Copper Wasp',
  'Chromium',
  'Beat Man',
  'Diecast',
  'Felina',
  'T0M8T0HE4D',
  'Reboot Man',
]);

const EASTER_VALENTINES_OUTFIT_NAMES = new Set([
  'Heartbreaker',
  'Bunny Brawler',
  'Rabbit Raider',
  'Lovethorn',
  'Pinkie',
  'Candyman',
  'Bun Bun',
  'Lovely',
  'Dutch',
  'Miss Bunny Penny',
  'Heartbreaker Shadow',
  'Hazard Hare',
  'Esme',
  'Ennui',
  'Queen of Hearts',
  'Love Ranger',
  'Stoneheart',
  'Oona Usagi',
  'Hopper',
  'Fallen Love Ranger',
  'Nitehare',
]);

const EASTER_VALENTINES_SETS = new Set(['Bunny Power 5']);

const FORESTRY_OUTFIT_NAMES = new Set([
  'Prickly Patroller',
  'Bushranger',
  'Toon Bushy',
  'Bloom',
  'Winterfest Bushranger',
  'Autumn',
  'Xerick',
  'Cursed Kodama',
  'Flytrap',
]);

const ANIMALS_OUTFIT_NAMES = new Set([
  'Fennix',
  'Doggo',
  'Hybrid',
  'Wukong',
  'Polar Patroller',
  'Axo',
  'Bryne',
  'Azuki',
  'Volpez',
  'Drakon Steel Hybrid',
  'Oscar',
  'Budge',
  'Sgt. Drake',
  'Tex Flamingo',
  'Rufus',
  'Lizzik',
  'Captain Talon',
  'Corvus',
  'Paulie Featherface',
  'Andy Fangerson',
  'Dark Doggo',
  'Flakey the Snowbird',
  'Hajime',
  'Boss Kōji',
  'Alphonse',
  'Chef',
  'Duke',
  'Flightalis',
  'Fetch',
  'Fletcher Kane',
  'Wave Rider Axo',
  'Skillet',
  'Courtside Axo',
  'Clyde',
  'Ziggy',
  'Dire',
  'War Wolf Dire',
  'Don Eggcracker',
  'Ken Kestrel',
  'Ural the Sage',
  'Kingston',
  'Cheeks',
  'Pingwin',
  'KD Rattical',
  'Squibbly',
  'Cluster',
  'Agent Patch',
  'Synthesis',
  'Fabio Sparklemane',
  'Safety First Steve',
  'Champion Drake',
  'Karasu',
  'The Goldfish',
  'J.B. Chimpanski',
  'Moisty Merman',
  'Cluck',
  'Dolph',
  'Wendell',
  'Dr. Theodore Flyesbee',
  'Wolfie',
  'Kozaru',
]);

const SPORTS_SETS = new Set(['Goalbound', 'Fearless Fairway', 'Let Them Know', 'Triple Threat']);

const SPORTS_OUTFIT_NAMES = new Set(['Jumpshot']);

const FIRE_AND_ICE_OUTFIT_NAMES = new Set([
  'Molten Battle Hound',
  'Molten Valkyrie',
  'Ruin',
  'Inferno',
  'Ember',
  'Molten Omen',
  'Frozen Love Ranger',
  'The Ice Queen',
  'The Ice King',
  'Shiver',
  'Blaze',
  'Snowheart',
  'Frost Broker',
  'Incinerator Kuno',
  'Molten Ragnarok',
  'Roast Lord',
  'Ice Crystal',
  'Permafrost Raider',
  'Frigid Foregoer',
  'Heartbreak Ranger',
  'Icy Metal Mouth',
  'Gale',
  'Exalted Ice King',
  'Pyreheart',
  'Lady Windfrost',
  'Molten Metal Mouth',
  'Lady Flamespark',
  'Lady Waveflow',
  'The Prisoner',
]);

const ASTRAL_ENTITIES_OUTFIT_NAMES = new Set([
  'Fusion',
  'Slumber ',
  'Infinity',
  'Galaxy',
  'Zero',
  'Cyclo',
  'Galaxy Scout',
  'Galaxia',
  'Iso',
  'Hedron',
  'Pulse',
  'Galaxy Grappler',
  'Koi Brawler Zero',
  'Axion Sentinel ',
  'Astrea',
  'Sunspot',
  'Andromeda',
  'Titan',
  'Tempest',
  'Corascana',
  'Mystica',
  'Cosmic Infinity',
  'Triarch Nox',
  'Triarch Aurora',
  'Flow',
]);

const ALIENS_OUTFIT_NAMES = new Set([
  'Zorgoton',
  'Madcap',
  'Kymera',
  'Joey',
  'Human Bill',
  'Trespasser Elite',
  'Geometrik',
  'The Cube Queen',
  'Cube Assassin',
  'The Herald',
  'Serenade',
  'Brainstorm',
  'Redcap',
  'Trespasser Defector',
  'Harlowe',
]);

const STUDENTS_AND_SORCERY_OUTFIT_NAMES = new Set([
  'Castor',
  'Elmira',
  'Luminos',
  'Delirium',
  'Dominion',
  'Blacklight',
  'Isabelle',
  'Grisabelle',
  'Krisabelle',
  'Blizzabelle',
  'Breezabelle',
]);

const STUDENTS_AND_SORCERY_SETS = new Set(['Academy Champions']);

const SUPERHERO_ORIGINALS_OUTFIT_NAMES = new Set([
  'Valor',
  'Carbide',
  'Haylee Skye',
  'Killswitch',
  'Lightrider',
  'Morgan Myst',
  'Jewel',
  'Afterburn',
  'Dex Diamond',
  'Umbra Nyte',
]);

const SUPERHERO_ORIGINALS_SETS = new Set(['Boundless', 'Fallen Heroes']);

const NO_SWEAT_SUMMER_OUTFIT_NAMES = new Set([
  'Ocean',
  'Laguna',
  'Sun Strider',
  'Sun Tan Specialist',
  'Chomp Sr.',
  'Comfy Chomps',
  'Cozy Chomps',
  'Surf Witch',
  'Summer Fable',
  'Tropical Punch Zoey',
  'Reef Ranger',
  'Trench Trawler',
  'King Krab',
  'Medley',
  'Riptide Raz',
  'Slayer Charlotte',
  'Undercover Kor',
  'Unstuffed Guff',
  'Coastal Machinist',
  'Tidewalker Trace',
  'Tide Strider',
  'Scuba Crystal',
  'Champion Surf Witch',
  'Malibu',
  'Surf Rider',
  'Wake Rider',
]);

const READY_TO_HEIST_OUTFIT_NAMES = new Set([
  'Heist',
  'Rapscallion',
  'Scoundrel',
  'Demi',
  'Goldie',
  'Hush',
  'Wild Card',
  'Dark Wild Card',
  'Aces Wild Card',
  'Double Agent Hush',
  'Dynamic Hush',
  'Chaos Double Agent',
  'Double Agent Wildcard',
  'Loveless',
  'Nolan Chance',
  'Paxton Price',
  'Antonia',
  'Piper Pace',
  'Alias',
  'Caper',
  'The Dealer',
  'Chaos Director',
  'Cassidy Quinn',
  'Valentina',
  'Keisha Cross',
]);

const IMAGINED_ORDER_OUTFIT_NAMES = new Set([
  'Doctor Slone',
  'Snow Stealth Slone',
  'Innovator Slone',
  'Vanguard Slone',
  'Singularity',
  'Zadie',
  'Shady Zadie',
  'Vanguard Zadie',
  'Elite Zadie',
  'Gunnar',
  'Huntmaster Saber',
  'Rook',
  'Shadow Ops',
  'Special Forces',
  'Maven',
  'Kor',
  'Panther',
  'Janice',
  'Chaos Agent',
  'Riot',
  'Kiara K.O.',
  'Dasha',
]);

const AEROSOL_AND_AURAS_OUTFIT_NAMES = new Set([
  'Teknique',
  'Tilted Teknique',
  'Street Wave Teknique',
  'Komplex',
  'Tectonic Komplex',
  'Abstrakt',
  'Night Artist Abstrakt',
  'Aura',
  'Fresh Aura',
  'Saura',
  'Treasured Aura',
]);

const THE_UNDERGROUND_OUTFIT_NAMES = new Set([
  'Hope',
  'Heroic Hope',
  'Shadow Blade Hope',
  'Rival Hope',
  'Valeria',
  'Montague',
  'Nisha',
]);

function isStudentsAndSorceryOutfit(outfit) {
  if (STUDENTS_AND_SORCERY_OUTFIT_NAMES.has(outfit.name)) return true;
  return STUDENTS_AND_SORCERY_SETS.has(outfit.setName ?? '');
}

function isSuperheroOriginalsOutfit(outfit) {
  if (SUPERHERO_ORIGINALS_OUTFIT_NAMES.has(outfit.name)) return true;
  return SUPERHERO_ORIGINALS_SETS.has(outfit.setName ?? '');
}

function isEasterValentinesOutfit(outfit) {
  if (EASTER_VALENTINES_OUTFIT_NAMES.has(outfit.name)) return true;
  return EASTER_VALENTINES_SETS.has(outfit.setName ?? '');
}

function isSportsOutfit(outfit) {
  const name = outfit.name ?? '';
  const setName = outfit.setName ?? '';
  if (SPORTS_OUTFIT_NAMES.has(name)) return true;
  if (name.includes('Alpine Ace')) return true;
  if (name.includes('Mogul Master')) return true;
  if (SPORTS_SETS.has(setName)) return true;
  if (name.includes('Triple Threat')) return true;
  return false;
}

export function getCatalogueSeriesKey(outfit) {
  if (ANIME_OUTFIT_NAMES.has(outfit.name)) return 'anime-legends';
  if (CARTOON_OUTFIT_NAMES.has(outfit.name)) return 'cartoon';
  if (TV_OUTFIT_NAMES.has(outfit.name)) return 'tv-legends';
  if (WWE_OUTFIT_NAMES.has(outfit.name)) return 'wwe-legends';
  if (OTHER_COLLAB_SKINS_OUTFIT_NAMES.has(outfit.name)) return 'other-collab-skins';
  if (GENERAL_COLLABORATIONS_OUTFIT_NAMES.has(outfit.name) || outfit.name.includes('NBA 75')) {
    return 'general-collaborations';
  }
  if (NFL_OUTFIT_NAMES.has(outfit.name)) return 'nfl';
  if (ANIME_ORIGINALS_OUTFIT_NAMES.has(outfit.name)) return 'anime-originals';
  if (NANNERS_OUTFIT_NAMES.has(outfit.name)) return 'nanners';
  if (JONESEYS_OUTFIT_NAMES.has(outfit.name)) return 'joneseys';
  if (BRITERS_AND_BOMBERS_OUTFIT_NAMES.has(outfit.name)) return 'briters-and-bombers';
  if (FISHIES_OUTFIT_NAMES.has(outfit.name)) return 'fishies';
  if (RAVENS_OUTFIT_NAMES.has(outfit.name)) return 'ravens';
  if (KITTIES_OUTFIT_NAMES.has(outfit.name)) return 'kitties';
  if (TEAM_LEADERS_OUTFIT_NAMES.has(outfit.name)) return 'team-leaders';
  if (KNIGHTS_OUTFIT_NAMES.has(outfit.name)) return 'knights';
  if (SPACE_VOYAGERS_OUTFIT_NAMES.has(outfit.name)) return 'space-voyagers';
  if (FOOD_OUTFIT_NAMES.has(outfit.name)) return 'food';
  if (TOYS_OUTFIT_NAMES.has(outfit.name)) return 'toys';
  if (ICON_OUTFIT_NAMES.has(outfit.name)) return 'icon';
  if (DANCERS_AND_DJS_OUTFIT_NAMES.has(outfit.name)) return 'dancers-and-djs';
  if (WINTERFEST_OUTFIT_NAMES.has(outfit.name)) return 'winterfest';
  if (FORTNIGHTMARES_OUTFIT_NAMES.has(outfit.name)) return 'fortnightmares';
  if (ROBOTS_OUTFIT_NAMES.has(outfit.name)) return 'robots';
  if (isEasterValentinesOutfit(outfit)) return 'easter-valentines';
  if (FORESTRY_OUTFIT_NAMES.has(outfit.name)) return 'forestry';
  if (ANIMALS_OUTFIT_NAMES.has(outfit.name)) return 'animals';
  if (isSportsOutfit(outfit)) return 'sports';
  if (FIRE_AND_ICE_OUTFIT_NAMES.has(outfit.name)) return 'fire-and-ice';
  if (ASTRAL_ENTITIES_OUTFIT_NAMES.has(outfit.name)) return 'astral-entities';
  if (ALIENS_OUTFIT_NAMES.has(outfit.name)) return 'aliens';
  if (isStudentsAndSorceryOutfit(outfit)) return 'students-and-sorcery';
  if (isSuperheroOriginalsOutfit(outfit)) return 'superhero-originals';
  if (NO_SWEAT_SUMMER_OUTFIT_NAMES.has(outfit.name)) return 'no-sweat-summer';
  if (READY_TO_HEIST_OUTFIT_NAMES.has(outfit.name)) return 'ready-to-heist';
  if (IMAGINED_ORDER_OUTFIT_NAMES.has(outfit.name)) return 'imagined-order';
  if (AEROSOL_AND_AURAS_OUTFIT_NAMES.has(outfit.name)) return 'aerosol-and-auras';
  if (THE_UNDERGROUND_OUTFIT_NAMES.has(outfit.name)) return 'the-underground';
  if (THE_SEVEN_OUTFIT_NAMES.has(outfit.name)) return 'the-seven';
  if (FOX_CLAN_OUTFIT_NAMES.has(outfit.name)) return 'fox-clan';
  if (MIDAS_FAMILY_OUTFIT_NAMES.has(outfit.name)) return 'midas-family';
  if (HIGH_STAKES_CLUB_OUTFIT_NAMES.has(outfit.name)) return 'high-stakes-club';
  if (RUBY_AND_OPAL_OUTFIT_NAMES.has(outfit.name)) return 'ruby-and-opal';
  if (GREEK_GODS_OUTFIT_NAMES.has(outfit.name)) return 'greek-gods';

  const raw = String(outfit.series ?? '').trim().toLowerCase();
  if (!raw) return 'other';
  if (raw.includes('dc')) return 'dc';
  if (raw.includes('marvel')) return 'marvel';
  if (raw.includes('icon')) return 'icon';
  if (raw.includes('gaming legends')) return 'gaming-legends';
  if (raw.includes('star wars')) return 'star-wars';
  return 'other';
}

export function groupOutfitsBySeries(outfits) {
  const buckets = new Map(SERIES_GROUPS.map((group) => [group.key, []]));

  for (const outfit of outfits) {
    buckets.get(getCatalogueSeriesKey(outfit)).push(outfit);
  }

  return SERIES_GROUPS.filter((group) => buckets.get(group.key).length > 0)
    .sort((a, b) => SERIES_ORDER.get(a.key) - SERIES_ORDER.get(b.key))
    .map((group) => ({
      key: group.key,
      label: group.label,
      outfits: sortOutfitsByNumber(buckets.get(group.key)),
    }));
}
