import { sortOutfitsByNumber } from './seasonSort';

export const SERIES_GROUPS = [
  { key: 'dc', label: 'DC' },
  { key: 'marvel', label: 'Marvel' },
  { key: 'icon', label: 'Icon' },
  { key: 'gaming-legends', label: 'Gaming Legends' },
  { key: 'star-wars', label: 'Star Wars' },
  { key: 'cartoon', label: 'Cartoon Legends' },
  { key: 'anime-legends', label: 'Anime Legends' },
  { key: 'tv-legends', label: 'TV Legends' },
  { key: 'wwe-legends', label: 'WWE Legends' },
  { key: 'other-collab-skins', label: 'Other Collab Skins' },
  { key: 'general-collaborations', label: 'General Collaborations' },
  { key: 'nfl', label: 'NFL' },
  { key: 'nanners', label: 'Nanners' },
  { key: 'joneseys', label: 'Joneseys' },
  { key: 'briters-and-bombers', label: 'Briters and Bombers' },
  { key: 'fishies', label: 'Fishies' },
  { key: 'kitties', label: 'Kitties' },
  { key: 'team-leaders', label: 'Team Leaders' },
  { key: 'knights', label: 'Knights' },
  { key: 'space-voyagers', label: 'Space Voyagers' },
  { key: 'the-seven', label: 'The Seven' },
  { key: 'high-stakes-club', label: 'High Stakes Club' },
  { key: 'other', label: 'Other' },
];

const SERIES_ORDER = new Map(SERIES_GROUPS.map((group, index) => [group.key, index]));

const CARTOON_OUTFIT_NAMES = new Set([
  'Rick Sanchez',
  'Mecha Morty',
  'Mr. Meeseeks',
  'Queen Summer',
  'Pickle Rick',
  'Rick Prime',
  'Space Beth',
  'Peter Griffin',
  'The Giant Chicken',
  'Cleveland Brown',
  'Lois Griffin',
  'Hank Hill',
  'Peggy Hill',
  'Bob Belcher',
  'Linda Belcher',
  'Danny Fenton',
  'Sam Manson',
  'Ed',
  'Mordecai',
  'Skips',
  'Eric Cartman',
  'Stan Marsh',
  'Kyle Broflovski',
  'Butters Stotch',
  'Kenny McCormick',
  'Homer Simpson',
  'Tighty Whities Homer',
  'Marge Simpson',
  'Lisa Simpson',
  'Bart Simpson',
  'Krusty the Clown',
  'Ned Flanders',
  'Scratchy',
  'Moe Szyslak',
  'Ben Tennyson',
  'Gwen Tennyson',
  'Invincible',
  'Omni-Man',
  'Atom Eve',
  'Dupli-Kate',
  'Allen the Alien',
  'Leonardo',
  'Michelangelo',
  'Donatello',
  'Raphael',
  'Shredder',
  'Super Shredder',
  "April O'Neil",
  'Casey Jones',
  'Bebop',
  'Rocksteady',
  "Krang's Android",
  'Korra',
  'Aang',
  'Katara',
  'Zuko',
  'Toph Beifong',
  'Avatar State Aang',
  'Buzz Lightyear',
  'Emperor Zurg',
  'Dr. Doofenshmirtz',
  'Buff Perry',
  'Frozone',
  'Mr. Incredible',
  'Mrs. Incredible',
  'Bugs Bunny',
  'Daffy Duck',
  'Lola Bunny',
  'Hercules',
  'Hades (Lord of the Dead)',
  'Megara',
  'He-Man',
  'She-Ra',
  'Skeletor',
  'Scooby-Doo',
  'Fred Jones',
  'Daphne Blake',
  'Velma Dinkley',
  'Shaggy Rogers',
  'Beavis',
  'Butt-Head',
  'Finn the Human',
  'Jake the Dog',
  'Princess Bubblegum',
  'Marceline',
  'Fionna the Human',
  'Cake the Cat',
  'Ice King',
  'The Earl of Lemongrab',
  'Hero Baymax',
  'Jack Skellington',
  'Sally',
  'Philip J. Fry',
  'Turanga Leela',
  'Bender Bending Rodríguez',
  'Pomni',
  'Jax',
  'Tom Lizard',
  'Cruella de Vil',
  'Captain Hook',
  'Maleficent',
]);

const ANIME_OUTFIT_NAMES = new Set([
  'Naruto Uzumaki',
  'Kakashi Hatake',
  'Sasuke Uchiha',
  'Sakura Haruno',
  'Itachi Uchiha',
  'Orochimaru',
  'Gaara',
  'Hinata Hyuga',
  'Son Goku',
  'Goku Black',
  'Bulma',
  'Beerus',
  'Vegeta',
  'Android 17',
  'Android 18',
  'Cell',
  'Frieza',
  'Son Gohan',
  'Piccolo',
  'Trunks',
  'Eren Jaeger',
  'Mikasa Ackermann',
  'Captain Levi',
  'All Might',
  'Izuku Midoriya',
  'Ochaco Uraraka',
  'Katsuki Bakugo',
  'Eijiro Kirishima',
  'Mina Ashido',
  'Shoto Todoroki',
  'Himiko Toga',
  'Dabi',
  'Tomura Shigaraki',
  'Kikoru Shinomiya',
  'Kafka Hibino',
  'Reno Ichikawa',
  'Yuji Itadori',
  'Streetwear Yuji Itadori',
  'Satoru Gojo',
  'Nobara Kugisaki',
  'Megumi Fushiguro',
  'Ryomen Sukuna',
  'Toji Fushiguro',
  'Mahito',
  'Saitama',
  'Terrible Tornado',
  'Genos',
  'Uryu Ishida',
  'Ichigo Kurosaki',
  'Rukia Kuchiki',
  'Orihime Inoue',
  'Spike Spiegel',
  'Faye Valentine',
]);

const TV_OUTFIT_NAMES = new Set([
  'Indiana Jones',
  'John Wick',
  'John Wick (Pen & Ink)',
  'Jon Snow',
  'Daenerys Targaryen',
  'Night King',
  'Black Dino Ranger',
  'White Dino Ranger',
  'Michael Scott',
  'Dwight Schrute',
  'Jules Winnfield',
  'Vincent Vega',
  'Doc Brown',
  'Marty McFly',
  'The Bride',
  'Yuki Yubari',
  'Gogo Yubari',
  'Vecna',
  'Mike Wheeler',
  'Will Byers',
  'Lucas Sinclair',
  'Dustin Henderson',
  'Xenomorph (Alien: Earth)',
  'Art the Clown',
  'Jason ',
  'The Grabber',
  'Ghost Face',
  'Ares (TRON)',
  'Lord Zedd',
  'Dino Megazord',
  'Yellow Ranger',
  'Black Ranger',
  'Pink Ranger',
  'Red Ranger',
  'Blue Ranger',
  'Green Ranger',
  'Front Man',
  'Games Guard',
  'Games Manager',
  'Negan',
  'Neytiri',
  'Jake Sully',
  'Leatherface',
  'Edward Scissorhands',
  'Billy',
  'Jack Sparrow',
  'Cursed Jack Sparrow',
  'Elizabeth Swann',
  'Captain Barbossa',
  'Davy Jones',
  'Michael Myers',
  'Megatron',
  'Bumblebee',
  'Optimus Prime',
  'Optimus Primal',
  'Adonis Creed',
  'Ash Williams',
  'RoboCop',
  'Nathan Drake',
  'Chloe Frazer',
  'Rick Grimes',
  'Paul Atreides',
  'Chani',
  "Frankenstein's Monster",
  'The Mummy',
  "Frankenstein's Bride",
  'Dude',
  'Mike Lowrey',
  'Xenomorph',
  'Godzilla Evolved',
  'Kong',
  'Mechagodzilla',
  'Ellen Ripley',
  'Snake Eyes',
  'T-800',
  'Sarah Connor',
  'Terminator',
  'Daryl Dixon',
  'Michonne',
  'El Chapulín Colorado',
  'Predator',
  'Chief Hopper',
  'Demogorgon',
]);

const OTHER_COLLAB_SKINS_OUTFIT_NAMES = new Set([
  'Tung Tung Tung Sahur',
  'Ballerina Cappuccina',
  'Plungerman',
  'Gildedguy',
  'Guggimon',
  'Janky',
  'Kelsier',
]);

const GENERAL_COLLABORATIONS_OUTFIT_NAMES = new Set([
  'Spirit Sniper',
  'Curse Buster',
  'Phantom Commando',
  'Specter Inspector',
  'Aura Analyzer',
  'Paranormal Guide',
  'Haunt Officer',
  'Ecto Expert',
  'Containment Specialist',
  'P.K.E. Ranger',
  'Rumblestrip',
  'Torque',
  'Marshal',
  'Powertrain',
  'RPM',
  'Camber',
  'Chicane',
  'Downforce',
  'Kickdown',
  'Circuit',
  'Guerrero Colorado',
  'Amazona Colorada',
  'Héroe Colorado',
  'Guerrera Colorada',
  'Agente Colorado',
  'Defensora Colorada',
  'Soldado Colorado',
  'Heroína Colorada',
  'Defensor Colorado',
  'Capitana Colorada',
  'Creature Caretaker',
  'Mischief Maker',
  'Knowledge Keeper',
  'Hallway Hero',
  'Fearless Friend',
  'Story Seeker',
  'Prank Prodigy',
  'Radiant Rebel',
  'Audacious Adventurer',
  'Dynamic Dreamer',
  'Gong-gi Great',
  'Flying Stone Fighter',
  'Jegi Juggler',
  'Pentathlon Perfector',
  'Glass Bridge Survivor',
  'Tug of War Titan',
  'Dalgona Destroyer',
  'Marble Maven',
  'Green Light Guardian',
  'Ddakji Defender',
  'Assist Maven',
  'Post Patroller',
  'Court Commander',
  'Layup Legend',
  'Rebound Warrior',
  'Trey Specialist',
  'Finesse Forward',
  'Board Crasher',
  'Court Controller',
  'Shuto Striker',
  'Mat Master',
  'Kumite Clasher',
  'Keri Commander',
  'Kata Captain',
  'Karateka Jones',
  'Heron Stance Hero',
  'Gi Guardian',
  'Dojo Defender',
  'Black Belt Brawler',
  'Splash Specialist',
  'Rebound Raider',
  'Rain Maker',
  'Half-Court Hero',
  'Fast Break',
  'Fadeaway',
  'Dynamo Dribbler',
  'Crossover Champion',
  'Buzzer Beater',
  'Upload',
  'Proxy',
  'Packet',
  'Io',
  'Firewall',
  'Datapath',
  'Cypher',
  'Commandline',
  'Bitstream',
  'Bandwidth',
  'Tiki Tackler',
  'Striker Specialist',
  'Shot Stopper',
  'Sgt. Sweeper',
  'Power Poacher',
  'Pitch Patroller',
  'Midfield Master',
  'Galactico',
  'Derby Dominator',
  'Breakaway',
]);

const NFL_OUTFIT_NAMES = new Set([
  'Pass Rush Ranger',
  'Scrimmage Scrapper',
  'Blitz Brigade',
  'Red Zone Renegade',
  'TD Titan',
  'Formation Fighter',
  'Punt Paragon',
  'Crossbar Crusher',
  'Snap Squad',
  'Trench Runner',
  'Fair Play',
  'Offside Officer',
  'Time-Out',
  'Elite Linesman',
  'Huddle Hero',
  'End Zone Expert',
  'Offense Overseer',
  'Replay Ranger',
  'Spiral Specialist',
  'Sideline Commander',
  'End Zone',
  'Gridiron',
  'Spike',
  'Blitz',
  'Rush',
  'Interceptor',
  'Juke',
  'Strong Guard',
  'Whistle Warrior',
  'Striped Soldier',
]);

const WWE_OUTFIT_NAMES = new Set([
  'Liv Morgan',
  'Stone Cold Steve Austin',
  'Cody Rhodes',
  'Undertaker',
  'Becky Lynch',
  'Bianca Belair',
  'John Cena',
]);

const NANNERS_OUTFIT_NAMES = new Set([
  'Peely',
  'Springfielder Peely',
  'Unpeely',
  'The Final Peel',
  'Island Adventure Peely',
  'Peelverine',
  'Peelosopher Bananocrates',
  'Adventure Peely',
  'KAWSPEELY',
  'Toon Peely',
  'Polar Peely',
  'P33LY',
  'Potassius Peels',
  'Agent Peely',
  'Peely Bone',
]);

const JONESEYS_OUTFIT_NAMES = new Set([
  'Ranger',
  'Captain Jones',
  'Vengeance Jones',
  'Championship Jonesy',
  'Jones Unchained',
  'Jonesy the Secondst',
  'Cozy Knit Jonesy',
  'Agent Jones',
  'Cozy Jonesy',
  'Jonesy The First',
  'Castaway Jonesy',
  'Relaxed Fit Jonesy',
  'Scuba Jonesy',
  'Slurp Jonesy',
  'Dark Jonesy',
  'Bunker Jonesy',
  'Guernsey',
  'Codename E.L.F.',
  'Lt. Evergreen',
]);

const BRITERS_AND_BOMBERS_OUTFIT_NAMES = new Set([
  'Brite Bomber',
  'Brite Gunner',
  'Brite Blaster',
  'Beach Bomber',
  'Brilliant Bomber',
  'Minty Bomber',
  'Britestorm Bomber',
  'Blizzard Bomber',
  'Froststorm Bomber',
  'Toon Bomber',
  'Brite Agent',
  'Brite Hunter',
  'BriteStar',
  'Brite Raider',
]);

const FISHIES_OUTFIT_NAMES = new Set([
  'Fishstick',
  'Triggerfish',
  'Frozen Fishstick',
  'Atlantean Fishstick',
  'Fishskull',
  'Fa-La-La-La-Fishstick',
  'Toona Fish',
  'Gummy Fishstick',
  'Fish Thicc',
  'Bogstick',
  'Fishdrift',
  'Fishpool',
  'Robo-Fishstick',
  'Blinky Fishstick',
  'Contract Giller',
]);

const KITTIES_OUTFIT_NAMES = new Set([
  'Kit',
  'Bad Kit',
  'Katt',
  'Spice',
  'Meowscles',
  'Toon Meowscles',
  'Meow Skulls',
  'Purradise Meowscles',
  'Phantom Meowscles',
  'Meowtooth',
  'Meowdas',
  'Cate Meowdy',
  'Neko-RX1',
  'Lynx',
  'NeuraLynx',
  'Renegade Lynx',
  'Trailblazer Lynx',
  'Void Walker Lynx',
]);

const TEAM_LEADERS_OUTFIT_NAMES = new Set([
  'Cuddle Team Rider',
  'Wookiee Team Leader',
  'Cuddle Team Specialist',
  'Gummi Team Leader',
  'Raven Team Leader',
  'Metal Team Leader',
  'Quackling',
  'Clover Team Leader',
  'Mecha Team Leader',
  'Spooky Team Leader',
  'P.A.N.D.A Team Leader',
  'Fireworks Team Leader',
  'Cuddle Team Leader',
  'Ragsy',
  'Mecha Cuddle Master',
  'Mecha Team Shadow',
  'Cuddlepool',
]);

const KNIGHTS_OUTFIT_NAMES = new Set([
  'Royale Knight',
  'Blue Squire',
  'Black Knight',
  'Red Knight',
  'Spider Knight',
  'Frozen Red Knight',
  'Ultima Knight',
  'Dark Red Knight ',
  'Rogue Spider Knight',
  'Eternal Knight',
  'Omega Knight',
  'Swamp Knight',
  'Core Knight Talus',
  'Spectra Knight',
  'Knightmare',
  'Ultima Carver',
  'Knight Conqueror',
  'Blitz Knight',
  'The Dark Maw',
]);

const SPACE_VOYAGERS_OUTFIT_NAMES = new Set([
  'Voyager Unleashed',
  'Dark Voyager (Reality Redacted)',
  'Dark Voyager',
  'Eternal Voyager',
  'Deo',
  'Siona',
  'Corrupted Voyager',
  'Eternal Wanderer',
  'Moonwalker',
  'Mission Specialist',
  'Leviathan',
  'Slurp Leviathan ',
]);

const THE_SEVEN_OUTFIT_NAMES = new Set([
  'The Imagined',
  'The Order',
  'The Guardian',
  'The Order (Reforged)',
  'The Foundation',
  'The Foundation (Reforged)',
  'The Visitor',
  'The Visitor (Reality Unknown)',
  'Paradigm (Reality-659)',
  'The Paradigm',
  'The Origin',
  'The Scientist',
]);

const HIGH_STAKES_CLUB_OUTFIT_NAMES = new Set([
  'Joni the Red',
  'Helsie',
  'Lucien West',
  'Joni the Scarlet',
  'Huntress Helsie',
  'Formal Lucien West',
  'Helsie Midnight',
  'Red Ruin Joni',
  'Lycan West',
]);

export function getCatalogueSeriesKey(outfit) {
  if (ANIME_OUTFIT_NAMES.has(outfit.name)) return 'anime-legends';
  if (CARTOON_OUTFIT_NAMES.has(outfit.name)) return 'cartoon';
  if (TV_OUTFIT_NAMES.has(outfit.name)) return 'tv-legends';
  if (WWE_OUTFIT_NAMES.has(outfit.name)) return 'wwe-legends';
  if (OTHER_COLLAB_SKINS_OUTFIT_NAMES.has(outfit.name)) return 'other-collab-skins';
  if (GENERAL_COLLABORATIONS_OUTFIT_NAMES.has(outfit.name) || outfit.name.includes('NBA 75')) {
    return 'general-collaborations';
  }
  if (NFL_OUTFIT_NAMES.has(outfit.name)) return 'nfl';
  if (NANNERS_OUTFIT_NAMES.has(outfit.name)) return 'nanners';
  if (JONESEYS_OUTFIT_NAMES.has(outfit.name)) return 'joneseys';
  if (BRITERS_AND_BOMBERS_OUTFIT_NAMES.has(outfit.name)) return 'briters-and-bombers';
  if (FISHIES_OUTFIT_NAMES.has(outfit.name)) return 'fishies';
  if (KITTIES_OUTFIT_NAMES.has(outfit.name)) return 'kitties';
  if (TEAM_LEADERS_OUTFIT_NAMES.has(outfit.name)) return 'team-leaders';
  if (KNIGHTS_OUTFIT_NAMES.has(outfit.name)) return 'knights';
  if (SPACE_VOYAGERS_OUTFIT_NAMES.has(outfit.name)) return 'space-voyagers';
  if (THE_SEVEN_OUTFIT_NAMES.has(outfit.name)) return 'the-seven';
  if (HIGH_STAKES_CLUB_OUTFIT_NAMES.has(outfit.name)) return 'high-stakes-club';

  const raw = String(outfit.series ?? '').trim().toLowerCase();
  if (!raw) return 'other';
  if (raw.includes('dc')) return 'dc';
  if (raw.includes('marvel')) return 'marvel';
  if (raw.includes('icon')) return 'icon';
  if (raw.includes('gaming legends')) return 'gaming-legends';
  if (raw.includes('star wars')) return 'star-wars';
  return 'other';
}

export function groupOutfitsBySeries(outfits) {
  const buckets = new Map(SERIES_GROUPS.map((group) => [group.key, []]));

  for (const outfit of outfits) {
    buckets.get(getCatalogueSeriesKey(outfit)).push(outfit);
  }

  return SERIES_GROUPS.filter((group) => buckets.get(group.key).length > 0)
    .sort((a, b) => SERIES_ORDER.get(a.key) - SERIES_ORDER.get(b.key))
    .map((group) => ({
      key: group.key,
      label: group.label,
      outfits: sortOutfitsByNumber(buckets.get(group.key)),
    }));
}
